# =====================================================
# EMAIL ALERT SYSTEM (WORKING VERSION)
# =====================================================

import smtplib
from email.mime.text import MIMEText

# ---------------- EMAIL CONFIG ----------------
SENDER="managercryptoportfolio@gmail.com"

# ⚠ IMPORTANT:
# Use Gmail APP PASSWORD (NOT normal password)
APP_PASS="PUT_YOUR_APP_PASSWORD_HERE"


# =====================================================
# SEND ALERT MAIL
# =====================================================
def send_alert(df):

    body=f"""
🚨 Crypto Risk Alert

High-risk cryptos detected:

{df.to_string(index=False)}

Generated by Crypto Investment Manager
"""

    msg=MIMEText(body)
    msg["Subject"]="🚨 Crypto Risk Alert"
    msg["From"]=SENDER
    msg["To"]=SENDER

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com",465) as server:
            server.login(SENDER,APP_PASS)
            server.send_message(msg)

    except Exception as e:
        print("Email error:",e)


# =====================================================
# SEND REGISTRATION MAIL
# =====================================================
def send_registration_mail(email,name):

    msg=MIMEText(f"Hello {name}, your registration is successful.")
    msg["Subject"]="Registration Successful"
    msg["From"]=SENDER
    msg["To"]=email

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com",465) as server:
            server.login(SENDER,APP_PASS)
            server.send_message(msg)

    except Exception as e:
        print("Email error:",e)
